import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { expect, test } from "vite-plus/test";
import { PdfDocument, isStream } from "../src/parse/pdf/document.ts";
import { PdfLexer, isDict, isName, latin1, toNumber } from "../src/parse/pdf/objects.ts";

/**
 * Fixtures are generated by `tests/fixtures/pdf/make-fixtures.mjs`; each one
 * isolates one structural feature of PDF-2, so a failure names the feature.
 */
const load = (name: string): Uint8Array =>
  new Uint8Array(readFileSync(fileURLToPath(new URL(`./fixtures/pdf/${name}`, import.meta.url))));

const open = (name: string) => PdfDocument.parse(load(name));
const asText = (bytes: Uint8Array) => latin1(bytes).trim();

test("reads a classic cross-reference table", async () => {
  const doc = await open("minimal.pdf");
  const pages = await doc.pages();
  expect(pages).toHaveLength(1);
  expect(asText(await doc.pageContent(pages[0] as never))).toBe("1 0 0 RG\n10 20 m 30 40 l S");
});

test("inflates a Flate stream whose /Length is an indirect reference", async () => {
  const doc = await open("flate-indirect-length.pdf");
  const pages = await doc.pages();
  expect(asText(await doc.pageContent(pages[0] as never))).toBe("0 0 1 rg\n0 0 50 50 re f");
});

/**
 * The join matters: these two parts split mid-number ("10 " + "10 m …"), so
 * concatenating without a separator would read "1010" as one token and lose
 * an operand (PDF 32000-1 §7.7.3.3).
 */
test("joins a /Contents array so no token spans the join", async () => {
  const doc = await open("contents-array.pdf");
  const pages = await doc.pages();
  const content = await doc.pageContent(pages[0] as never);
  // The property that matters is lexical, not textual: the trailing "10 " of
  // part one and the leading "10" of part two must stay two operands.
  const lexer = new PdfLexer(content);
  expect(lexer.parseObject()).toBe(10);
  expect(lexer.parseObject()).toBe(10);
  expect(lexer.parseObject()).toEqual({ op: "m" });
  expect(latin1(content)).not.toContain("1010");
});

test("inherits /Resources and /MediaBox from an ancestor node", async () => {
  const doc = await open("inherited-attrs.pdf");
  const [page] = await doc.pages();
  const box = await doc.array(page?.get("MediaBox"));
  expect(box.map((v) => toNumber(v))).toEqual([0, 0, 300, 300]);
  const resources = await doc.dict(page?.get("Resources"));
  const fonts = await doc.dict(resources?.get("Font"));
  expect(fonts?.has("F1")).toBe(true);
});

test("reads a cross-reference stream, object streams, and a PNG predictor", async () => {
  const doc = await open("xref-stream-objstm.pdf");
  const pages = await doc.pages();
  expect(pages).toHaveLength(1);
  // The catalog, pages node, and page all live inside the object stream.
  const root = await doc.dict(doc.trailerValue("Root"));
  const type = root?.get("Type");
  expect(isName(type) && type.name === "Catalog").toBe(true);
  expect(asText(await doc.pageContent(pages[0] as never))).toBe("0 0 0 RG\n5 5 m 95 95 l S");
});

test("follows a /Prev chain, newest section winning", async () => {
  const doc = await open("incremental-update.pdf");
  const pages = await doc.pages();
  // Object 4 is redefined by the update; the newer content must win.
  expect(asText(await doc.pageContent(pages[0] as never))).toBe("9 9 m 8 8 l S");
});

test("recovers from a cross-reference table that points nowhere", async () => {
  const doc = await open("broken-xref.pdf");
  const pages = await doc.pages();
  expect(pages).toHaveLength(1);
  expect(asText(await doc.pageContent(pages[0] as never))).toBe("3 3 m 7 7 l S");
});

// PDF-1: a signature is not encryption. This file carries a signature
// dictionary and must load normally — the Ghent X-4 suite is signed, so a
// false rejection here would reject the acceptance corpus.
test("a signed but unencrypted file exposes no /Encrypt and loads", async () => {
  const doc = await open("signed-not-encrypted.pdf");
  expect(doc.trailerValue("Encrypt")).toBeUndefined();
  const pages = await doc.pages();
  expect(asText(await doc.pageContent(pages[0] as never))).toBe("1 1 m 9 9 l S");
});

// The gate itself lands in 1.2; the object layer only has to surface the fact.
test("an encrypted file is detectable from the trailer", async () => {
  const doc = await open("encrypted.pdf");
  expect(doc.trailerValue("Encrypt")).toBeDefined();
});

test("rejects input that is not a PDF at all", async () => {
  await expect(PdfDocument.parse(new TextEncoder().encode("not a pdf"))).rejects.toThrow(
    /not a readable pdf/i,
  );
});

test("resolves references and reports stream objects", async () => {
  const doc = await open("minimal.pdf");
  const root = await doc.dict(doc.trailerValue("Root"));
  const pagesNode = await doc.dict(root?.get("Pages"));
  expect(isDict(pagesNode)).toBe(true);
  const kids = await doc.array(pagesNode?.get("Kids"));
  expect(kids).toHaveLength(1);
  const contents = (await doc.dict(kids[0]))?.get("Contents");
  const stream = await doc.getObject((contents as { num: number }).num);
  expect(isStream(stream)).toBe(true);
});

test("array() normalizes a lone value into a one-element array", async () => {
  const doc = await open("minimal.pdf");
  expect(await doc.array(undefined)).toEqual([]);
  expect(await doc.array(42)).toEqual([42]);
  expect(await doc.array([1, 2])).toEqual([1, 2]);
});
